name: cellprofiler

channels:
- conda-forge
- anaconda
- bioconda
- defaults

dependencies:
- python=3.8
- pip
- numpy=1.23.0
- matplotlib
- pandas
- mysqlclient
- openjdk
- scikit-learn
- mahotas
- gtk2
- gtk3
- Jinja2=3.0.1
- inflect=5.3.0
- wxpython=4.2.1
- mysqlclient=1.4.4
- sentry-sdk=0.18.0
- ipykernel
- cellprofiler=4.2.1
- pip:
    - cellpose==2.2.2
    - cellpose[gui]
    - csbdeep
    - stardist